spring.application.name=fairshare-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fairshare
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.security.user.name=user
spring.security.user.password=6b46f9fb-1356-42f9-9bbd-89e95901e401